name: app_jam
description: Google Uygulama Akademisi App Jam Flutter Projesi.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.14.0 # firebase packages
  firebase_auth: ^4.16.0
  firebase_core: ^2.10.0
  google_sign_in: ^6.1.6
  firebase_storage: ^11.6.0
  connectivity: ^3.0.6 #connection internet

  get: ^4.6.6

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true
  assets:
    - assets/istanbul.jpg
    - assets/uyLogo.jpg
